"""Add Comments and Cascade Actions

Revision ID: fd0b1ddb9f44
Revises: 7187d58b6bcf
Create Date: 2026-04-22 16:59:23.285354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd0b1ddb9f44'
down_revision: Union[str, Sequence[str], None] = '7187d58b6bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
